services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sentry_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db/door_control
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: https://rynix.ir/api
        VITE_WS_URL: wss://rynix.ir/ws/frontend
    container_name: sentry_frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:15-alpine
    container_name: sentry_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: door_control
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d door_control" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data_new:
