"""add_performance_indices

Revision ID: 5c60813a6ca3
Revises: 8cec9d931ed4
Create Date: 2025-12-11 15:20:31.231717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c60813a6ca3'
down_revision = '8cec9d931ed4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_admin_users_last_ip'), 'admin_users', ['last_ip'], unique=False)
    op.create_index(op.f('ix_admin_users_last_login'), 'admin_users', ['last_login'], unique=False)
    op.create_index(op.f('ix_mobile_otp_expires_at'), 'mobile_otp', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mobile_otp_expires_at'), table_name='mobile_otp')
    op.drop_index(op.f('ix_admin_users_last_login'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_last_ip'), table_name='admin_users')
    # ### end Alembic commands ###
