"""add_oauth_otp_fields

Revision ID: 8cec9d931ed4
Revises: 
Create Date: 2025-12-11 15:17:57.445893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cec9d931ed4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('admin_users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('admin_users', sa.Column('login_method', sa.String(), nullable=True))
    op.add_column('admin_users', sa.Column('last_ip', sa.String(), nullable=True))
    op.add_column('admin_users', sa.Column('last_user_agent', sa.String(), nullable=True))
    op.create_index(op.f('ix_admin_users_google_id'), 'admin_users', ['google_id'], unique=True)
    op.create_index(op.f('ix_admin_users_phone'), 'admin_users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_users_phone'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_google_id'), table_name='admin_users')
    op.drop_column('admin_users', 'last_user_agent')
    op.drop_column('admin_users', 'last_ip')
    op.drop_column('admin_users', 'login_method')
    op.drop_column('admin_users', 'phone')
    op.drop_column('admin_users', 'google_id')
    # ### end Alembic commands ###
