import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fa' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  fa: {
    appName: 'SentryGate',
    connected: 'متصل',
    connectionLost: 'ارتباط با سرور قطع شد',
    unlockCommandSent: 'دستور باز کردن ارسال شد',
    dashboard: 'داشبورد',
    accessGranted: 'دسترسی داده شد',
    accessDenied: 'دسترسی رد شد',
    unknown: 'ناشناس',
    register: 'ثبت‌نام',
    registerNewCard: 'ثبت کارت جدید',
    temperature: 'دما',
    ping: 'پینگ',
    loading: 'در حال بارگذاری...',
    serverRoom: 'اتاق سرور آلفا-۷',
    offline: 'آفلاین',
    accessLogs: 'گزارش دسترسی',
    users: 'کاربران',
    settings: 'تنظیمات',
    home: 'خانه',
    logs: 'گزارش‌ها',
    pressAndHold: 'نگه دارید تا باز شود',
    holdToUnlock: 'نگه‌داری برای باز کردن قفل...',
    unlocking: 'در حال باز کردن...',
    unlocked: 'باز شد',
    lockingIn: 'قفل در',
    seconds: 'ثانیه',
    humidity: 'رطوبت',
    good: 'عالی',
    warning: 'هشدار',
    normal: 'عادی',
    success: 'موفق',
    error: 'خطا',
    pending: 'در انتظار',
    realTimeMonitoring: 'پایش لحظه‌ای',
    activeFilters: 'فیلتر فعال',
    searchLogs: 'جستجو...',
    items: 'مورد',
    all: 'همه',
    reset: 'بازنشانی',
    noResults: 'نتیجه‌ای یافت نشد',
    clearFilters: 'پاک کردن فیلترها',
    web: 'وب',
    fullName: 'نام و نام خانوادگی',
    email: 'ایمیل',
    security: 'امنیت',
    currentPassword: 'رمز عبور فعلی',
    cancel: 'انصراف',
    saveChanges: 'ذخیره تغییرات',
    editProfile: 'ویرایش پروفایل',
    authorizedUsers: 'کاربران مجاز',
    levelClearance: 'سطح دسترسی',
    viewLogs: 'مشاهده لاگ',
    edit: 'ویرایش',
    delete: 'حذف',
    suspend: 'تعلیق',
    online: 'آنلاین',
    busy: 'مشغول',
    total: 'کل',
    searchTooltip: 'جستجو بر اساس نام، مکان یا دستگاه',
    admin: 'مدیر',
    operator: 'اپراتور',
    guest: 'مهمان',
    currentUser: 'کاربر فعلی',
    systemAdmin: 'مدیر سیستم',
    systemOperator: 'اپراتور سیستم',
    guestUser: 'کاربر مهمان',
    systemSettings: 'تنظیمات سیستم',
    autoLockTimeout: 'قفل خودکار شبانه',
    autoLockDesc: 'تنظیم ساعات قفل اضطراری',
    accessNotifications: 'اعلان‌های دسترسی',
    auditMode: 'حالت ممیزی',
    biometricAuth: 'احراز هویت بیومتریک',
    biometricDesc: 'نیاز به FaceID/TouchID',
    biometricPrompt: 'لطفاً هویت خود را تأیید کنید',
    biometricFailed: 'احراز هویت ناموفق بود',
    language: 'زبان',
    defaultConfiguration: 'تنظیمات پیش‌فرض',
    defaultConfigDesc: 'تنظیمات اولیه سیستم',
    defaultTheme: 'تم پیش‌فرض',
    selectTheme: 'انتخاب تم',
    defaultLanguage: 'زبان پیش‌فرض',
    selectLanguage: 'انتخاب زبان',
    timerDuration: 'مدت زمان تایمر',
    theme_neon: 'نئون',
    theme_matrix: 'ماتریکس',
    theme_light: 'روشن',
    duressMode: 'حالت اجبار (پنیک)',
    duressDesc: 'هشدار مخفی هنگام فشار',
    duressWarning: '⚠️ هشدار مخفی برای مدیران ارسال می‌شود',
    duress: 'اضطرار',
    duressAlert: 'اجبار',
    duressAlertSent: '🚨 هشدار اجباری ارسال شد!',
    duressAlertDetailed: 'این دسترسی تحت فشار انجام شده است',
    secureModeActive: '🛡️ حالت امنیتی فعال است',
    secureModeDesc: 'دسترسی در ساعات شبانه محدود شده',
    startTime: 'ساعت شروع',
    endTime: 'ساعت پایان',
    timestamp: 'زمان',
    location: 'موقعیت',
    device: 'دستگاه',
    systemStatus: 'وضعیت سیستم',
    uptime: 'زمان فعالیت',
    version: 'نسخه',
    recentActivity: 'فعالیت های اخیر',
    last24Hours: '۲۴ ساعت گذشته',
    systemHealth: 'سلامت سیستم',
    cpu: 'پردازنده',
    memory: 'حافظه',
    network: 'شبکه',
    login: 'ورود',
    logout: 'خروج',
    username: 'نام کاربری',
    password: 'رمز عبور',
    rememberMe: 'مرا به خاطر بسپار',
    forgotPassword: 'فراموشی رمز عبور؟',
    loginSuccess: 'ورود موفقیت‌آمیز!',
    invalidCredentials: 'نام کاربری یا رمز عبور اشتباه است',
    loginError: 'خطا در ورود به سیستم',
    usernamePlaceholder: 'نام کاربری را وارد کنید',
    passwordPlaceholder: 'رمز عبور را وارد کنید',
    role: 'نقش',
    clearanceLevel: 'سطح دسترسی',
    lastLogin: 'آخرین ورود',
    profileSettings: 'تنظیمات پروفایل',
    otpLogin: 'ورود با کد یکبار مصرف',
    otpDescription: 'کد یکبار مصرف به شماره شما ارسال می‌شود',
    phone: 'شماره موبایل',
    phonePlaceholder: '09123456789',
    sendOTP: 'ارسال کد',
    otpSent: 'کد یکبار مصرف ارسال شد',
    otpError: 'خطا در ارسال کد',
    invalidOTP: 'کد وارد شده نامعتبر است',
    otpVerifyError: 'خطا در تأیید کد',
    otpExpires: 'زمان باقی‌مانده',
    resendOTP: 'ارسال مجدد کد',
    loginWithOTP: 'ورود با کد یکبار مصرف',
    sending: 'در حال ارسال...',
    '2faVerification': 'تأیید دو مرحله‌ای',
    '2faDescription': 'کد تأیید را از برنامه احراز هویت خود وارد کنید',
    '2faInstruction': 'کد ۶ رقمی را از برنامه احراز هویت خود وارد کنید',
    invalid2FA: 'کد تأیید نامعتبر است',
    '2faError': 'خطا در تأیید دو مرحله‌ای',
    passwordRecovery: 'بازیابی رمز عبور',
    recoveryDescription: 'رمز عبور جدید خود را وارد کنید',
    verificationCode: 'کد تأیید',
    newPassword: 'رمز عبور جدید',
    confirmPassword: 'تأیید رمز عبور',
    passwordMismatch: 'رمز عبور و تأیید آن یکسان نیستند',
    passwordResetSuccess: 'رمز عبور با موفقیت تغییر یافت',
    passwordResetError: 'خطا در تغییر رمز عبور',
    resetPassword: 'تغییر رمز عبور',
    resetting: 'در حال تغییر...',
    rfidRequired: 'تگ RFID الزامی است',
    nameRequired: 'نام الزامی است',
    userRegistered: 'کاربر با موفقیت ثبت شد',
    enterName: 'نام را وارد کنید...',
    addUser: 'افزودن کاربر',
    fetchUsersFailed: 'خطا در دریافت لیست کاربران',
    noUsers: 'کاربری یافت نشد',
    confirmDelete: 'آیا از حذف این کاربر اطمینان دارید؟',
    userDeleted: 'کاربر حذف شد',
    deleteFailed: 'خطا در حذف کاربر',
    or: 'یا',
    backToLogin: 'بازگشت به ورود',
    defaultCredentials: 'اطلاعات ورود پیش‌فرض',
    loginDescription: 'لطفاً اطلاعات خود را وارد کنید',
    save: 'ذخیره',
    close: 'بستن',
  },
  en: {
    appName: 'SentryGate',
    connected: 'Connected',
    connectionLost: 'Connection lost',
    unlockCommandSent: 'Unlock command sent',
    dashboard: 'Dashboard',
    accessGranted: 'Access Granted',
    accessDenied: 'Access Denied',
    unknown: 'Unknown',
    register: 'Register',
    registerNewCard: 'Register New Card',
    temperature: 'Temperature',
    ping: 'Ping',
    loading: 'Loading...',
    serverRoom: 'Server Room Alpha-7',
    offline: 'Offline',
    accessLogs: 'Access Logs',
    users: 'Users',
    settings: 'Settings',
    home: 'Home',
    logs: 'Logs',
    pressAndHold: 'Press and hold to unlock',
    holdToUnlock: 'Hold to unlock...',
    unlocking: 'Unlocking...',
    unlocked: 'Unlocked',
    lockingIn: 'Locking in',
    seconds: 'seconds',
    humidity: 'Humidity',
    good: 'good',
    warning: 'warning',
    normal: 'normal',
    success: 'success',
    error: 'error',
    pending: 'pending',
    realTimeMonitoring: 'Real-time Monitoring',
    activeFilters: 'Active Filters',
    searchLogs: 'Search...',
    items: 'items',
    all: 'All',
    reset: 'Reset',
    noResults: 'No results found',
    clearFilters: 'Clear Filters',
    web: 'Web',
    fullName: 'Full Name',
    email: 'Email',
    security: 'Security',
    currentPassword: 'Current Password',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    editProfile: 'Edit Profile',
    authorizedUsers: 'Authorized Users',
    levelClearance: 'Level Clearance',
    viewLogs: 'View Logs',
    edit: 'Edit',
    delete: 'Delete',
    suspend: 'Suspend',
    online: 'Online',
    busy: 'Busy',
    total: 'Total',
    searchTooltip: 'Search by name, location, or device',
    admin: 'Admin',
    operator: 'Operator',
    guest: 'Guest',
    currentUser: 'Current User',
    systemAdmin: 'System Admin',
    systemOperator: 'System Operator',
    guestUser: 'Guest User',
    systemSettings: 'System Settings',
    autoLockTimeout: 'Auto-Lock Schedule',
    autoLockDesc: 'Set emergency lockdown hours',
    accessNotifications: 'Access Notifications',
    auditMode: 'Audit Mode',
    biometricAuth: 'Biometric Authentication',
    biometricDesc: 'Require FaceID/TouchID',
    biometricPrompt: 'Please verify your identity',
    biometricFailed: 'Authentication failed',
    language: 'Language',
    defaultConfiguration: 'Default Configuration',
    defaultConfigDesc: 'Initial system settings',
    defaultTheme: 'Default Theme',
    selectTheme: 'Select Theme',
    defaultLanguage: 'Default Language',
    selectLanguage: 'Select Language',
    timerDuration: 'Timer Duration',
    theme_neon: 'Neon',
    theme_matrix: 'Matrix',
    theme_light: 'Light',
    duressMode: 'Duress Mode (Panic)',
    duressDesc: 'Silent alert under coercion',
    duressWarning: '⚠️ Silent alert will be sent to administrators',
    duress: 'Duress',
    duressAlert: 'Duress',
    duressAlertSent: '🚨 Duress alert sent!',
    duressAlertDetailed: 'This access was performed under duress',
    secureModeActive: '🛡️ Secure Mode Active',
    secureModeDesc: 'Access restricted during night hours',
    startTime: 'Start Time',
    endTime: 'End Time',
    timestamp: 'Time',
    location: 'Location',
    device: 'Device',
    systemStatus: 'System Status',
    uptime: 'Uptime',
    version: 'v',
    recentActivity: 'Recent Activity',
    last24Hours: 'Last 24 Hours',
    systemHealth: 'System Health',
    cpu: 'CPU',
    memory: 'Memory',
    network: 'Network',
    login: 'Login',
    logout: 'Logout',
    username: 'Username',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    loginSuccess: 'Login successful!',
    invalidCredentials: 'Invalid username or password',
    loginError: 'Login error',
    usernamePlaceholder: 'Enter username',
    passwordPlaceholder: 'Enter password',
    role: 'Role',
    clearanceLevel: 'Clearance Level',
    lastLogin: 'Last Login',
    profileSettings: 'Profile Settings',
    otpLogin: 'Login with OTP',
    otpDescription: 'One-time password will be sent to your number',
    phone: 'Phone Number',
    phonePlaceholder: '09123456789',
    sendOTP: 'Send Code',
    otpSent: 'OTP sent successfully',
    otpError: 'Error sending OTP',
    invalidOTP: 'Invalid OTP code',
    otpVerifyError: 'Error verifying OTP',
    otpExpires: 'Time remaining',
    resendOTP: 'Resend code',
    loginWithOTP: 'Login with OTP',
    sending: 'Sending...',
    '2faVerification': '2FA Verification',
    '2faDescription': 'Enter the code from your authenticator app',
    '2faInstruction': 'Enter the 6-digit code from your authenticator app',
    invalid2FA: 'Invalid verification code',
    '2faError': 'Two-factor authentication error',
    passwordRecovery: 'Password Recovery',
    recoveryDescription: 'Enter your new password',
    verificationCode: 'Verification Code',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    passwordMismatch: 'Passwords do not match',
    passwordResetSuccess: 'Password changed successfully',
    passwordResetError: 'Error changing password',
    resetPassword: 'Reset Password',
    resetting: 'Resetting...',
    rfidRequired: 'RFID Tag is required',
    nameRequired: 'Name is required',
    userRegistered: 'User registered successfully',
    enterName: 'Enter name...',
    addUser: 'Add User',
    fetchUsersFailed: 'Failed to fetch users',
    noUsers: 'No users found',
    confirmDelete: 'Are you sure you want to delete this user?',
    userDeleted: 'User deleted',
    deleteFailed: 'Failed to delete user',
    or: 'or',
    backToLogin: 'Back to login',
    defaultCredentials: 'Default Credentials',
    loginDescription: 'Please enter your credentials',
    save: 'Save',
    close: 'Close',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('fa');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.fa] || key;
  };

  const isRTL = language === 'fa';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}